-- V9__add_gap_analysis_column.sql
-- Stores structured resume-to-JD gap analysis as JSONB.
-- Format: {"resumeCovers": [...], "resumeLacks": [...], "summary": "..."}
-- Generated by Gemini after computing the match score.
-- This makes the match score actionable — users see exactly what skills
-- their resume covers and what it's missing for each specific job.

ALTER TABLE applications ADD COLUMN gap_analysis JSONB;
